server:
  servlet:
    context-path: /project
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
spring:
#  datasource:
#    sql-script-encoding: UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: url
#    username: user
#    password: ****
  devtools: # 배포 시 주석처리
    restart:
      enabled: false
    livereload:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true